In [2]:
def crawl_website(url: str) -> str:
  
  try:
    resposta = requests.get(url=URL)
    resposta.raise_for_status()
  except HTTPError as exc:
    print(exc)
  else:
    return resposta.text

In [4]:
import re
import requests
from bs4 import BeautifulSoup

robots = []
URL = 'https://github.com/robots.txt'

robots = crawl_website(url=URL)

In [5]:
conteudo = None
URL = 'https://github.com/trending'
conteudo = crawl_website(url=URL)

In [6]:
import csv

with open(file='trending.html', mode='w', encoding='utf8') as fp:
  fp.write(conteudo)

In [44]:
pagina = BeautifulSoup(open('trending.html', mode='r'), 'html.parser')

In [45]:
# Desenvolvendo o exercício através da correção:

tabela = pagina.find_all('article')

project = []
language = []
stars = []
stars_today = []
forks = []

for item in tabela:
  # Nome do projeto:
  project.append(item.find('h1',{'class': 'h3 lh-condensed'}).get_text().strip().replace('\n','').replace(' ',''))
  # Linguagem utilizada:
  linguagem = item.find('span',{'itemprop': 'programmingLanguage'})
  try:
    linguagem = linguagem.get_text()
  except AttributeError:
    linguagem = ''
  language.append(linguagem)
  # Stars e Forks recebidos:
  conjunto = item.find_all('a',{'class': 'Link--muted d-inline-block mr-3'})
  stars.append(conjunto[0].get_text().replace(',','').strip())
  forks.append(conjunto[1].get_text().replace(',','').strip())
  # Stars_today recebidos:
  stars_today.append(item.find('span',{'class': 'd-inline-block float-sm-right'}).get_text().replace('stars today','').strip())

project = project[0:10]
language = language[0:10]
stars = stars[0:10]
stars_today = stars_today[0:10]
forks = forks[0:10]

ranking = []
for i in range(1, 11):
  ranking.append(i)

In [47]:
import csv
import pandas as pd

with open(file='github.csv', mode='w', encoding='utf8') as fp:
   escritor_csv = csv.writer(fp, delimiter=';')
   escritor_csv.writerow(['ranking','project','language','stars','stars_today','forks'])
   for i in range(len(ranking)):
     escritor_csv.writerow([ranking[i],project[i],language[i],stars[i],stars_today[i],forks[i]])

print(escritor_csv)

<_csv.writer object at 0x7fbc334b6270>

In [48]:
github_df = pd.read_csv('github.csv', sep=';')

In [53]:
github_df.head(n=10)

,ranking,project,language,stars,stars_today,forks
0,1,alibaba/lowcode-engine,TypeScript,9484,161,1587
1,2,alexbatalov/fallout1-ce,C++,564,183,21
2,3,lllyasviel/ControlNet,Python,1264,338,85
3,4,annfelix/DEVOPS-WORLD,NaN,1467,36,960
4,5,TheR1D/shell_gpt,Python,1047,566,41
5,6,acantril/learn-cantrill-io-labs,Python,3466,32,1374
6,7,google/styleguide,HTML,33581,135,13026
7,8,acheong08/EdgeGPT,Python,1259,282,106
8,9,alexbatalov/fallout2-ce,C++,513,58,42
9,10,palera1n/palera1n-c,C,119,39,13

In [54]:
github_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ranking      10 non-null     int64
 1   project      10 non-null     object
 2   language     9 non-null      object
 3   stars        10 non-null     int64
 4   stars_today  10 non-null     int64
 5   forks        10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 608.0+ bytes

In [57]:
github_df[['stars','forks']].describe().T

       count    mean           std    min     25%     50%      75%      max
stars   10.0  5276.4  10318.621271  119.0  684.75  1261.5  2966.25  33581.0
forks   10.0  1725.5   4017.375242   13.0   41.25    95.5  1270.50  13026.0

In [58]:
github_df.query('language == "Python" & stars_today > 300')

   ranking                project language  stars  stars_today  forks
2        3  lllyasviel/ControlNet   Python   1264          338     85
4        5       TheR1D/shell_gpt   Python   1047          566     41